### PR TITLE
Add mapping between classifiers and versions

### PR DESCRIPTION
**Pull request by toutpt**
It is really boring that we specify in setup.py the version of Plone supported using classifiers and need to do it by hand in the plonesoftware center.

Here I have added a mapping to support this directly. I would be glade that someone review this change and apply it. If no changes and no discussion happens I will merge it myself in one week.

Any feedback welcomed

### CODE REVIEW

**Comment by keul** [comment]
This is long long long wanted feature!

**Comment by davisagli** [comment]
This assumes any pypi classifier with a number in it corresponds to a Plone version. Shouldn't we limit it to the classifiers that start with "Framework :: Plone ::" ?

**Comment by aclark4life** [comment]
AFAICT what @davisagli says is true, however getClassifiers appears to get the classifiers for a particular PSC release (vs. going through every classifier on PyPI) so I'm not too worried about limiting to "Framework :: Plone ::" in this case. Athough it probably couldn't hurt, and it may make the intention of the code much clearer. +1 for merge.

**Comment by davisagli** [comment]
Actually I don't understand this pull request at all. It doesn't look like PSC releases have a field called classifiers, and even if they did, I assume it would be the full PyPI trove classifiers rather than anything that could be converted to a Decimal.

**Comment by toutpt** [comment]
@davisagli classifiers are provided with acquissition from psc configuration and default is a decimal. this code is the minimal to work without change any data on plone.org

and it works on a clean empty setup in localhost with all configuration to default.

**Comment by mauritsvanrees** [comment]
I have tried this locally and it seems to work fine.

Ah, a problem can be if there are rows in the classifiers field of the PSC object that have nothing to do with Plone but that have an id that is a Plone version.  Case in point is this one:

`3|3|Programming Language :: Python :: 3`

So if your setup.py uses the Python 3 classifier, then the `3` classifier will get set on the Project.  And with this pull request `Plone 3` will get set in the compatibility field.  I tried this locally and this is indeed the case, which is of course not wanted.

@toutpt: It may be better to get `self.request.form.get('classifiers')` in your method instead of `release.getClassifiers()`.  Then iterate over that list and check for items of the form `Framework :: Plone :: X.Y`

**Comment by toutpt** [comment]
I have done some change to use the request as mentionned and filter classifiers on 'Framework :: Plone :: '

Is this good now ?

**Comment by mauritsvanrees** [comment]
+1 for merging. Looks good to me and works when I try it locally. I have wanted this for a long time. Thanks!

I am not sure what the normal procedure here is, as a release would have to be made and plone.org would need to be updated too, after updating a test server, and I can't do that.

**Comment by aclark4life** [comment]
It's being discussed on the product-developers list, please chime in there.

**Pull request merged**
